0.2.19 - Up JCommander version + refactoring

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -108,19 +108,25 @@ Deploy Buggy:
   tags:
     - touchbit-shell
   before_script:
+    - mvn versions:set -DnewVersion=$CI_COMMIT_TAG
     - mvn dependency:purge-local-repository@local-buggy
     - mvn dependency:get@current-version && CHECK_RESULT=$(echo $?) || CHECK_RESULT=$(echo $?)
     - >
       if [ "${CHECK_RESULT}" != 1 ]; then
-        BUGGY_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
-        echo "[ERROR] The current version of Buggy ($BUGGY_VERSION) already exists in the TouchBIT repository"
-        echo "To set the new version, use the command: 'mvn versions:set -DnewVersion=<new version>'"
-        echo "Versioning rules: https://semver.org/spec/v2.0.0-rc.2.html"
-        false
+          if [[ "${CI_COMMIT_MESSAGE,,}" = *"force deploy"* ]]; then
+              echo "Force deploy tag version: ${CI_COMMIT_TAG}";
+          else
+              BUGGY_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
+              echo "[ERROR] The current version of Buggy ($BUGGY_VERSION) already exists in the TouchBIT repository"
+              echo "To set the new version, use the command: 'mvn versions:set -DnewVersion=<new version>'"
+              echo "Versioning rules: https://semver.org/spec/v2.0.0-rc.2.html"
+              false
+          fi
       fi
   only:
     - tags
   script:
+    - mvn versions:set -DnewVersion=$CI_COMMIT_TAG
     - mvn deploy -Dmaven.test.skip=true
     - BUGGY_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
     - "curl -X POST \"https://api.telegram.org/bot$BABBLER_TOKEN/sendMessage?chat_id=$TELEGRAM_BUGGY_CI_CD_CHAT_ID&disable_notification=false&parse_mode=Markdown&text=*Buggy*%0ANew version deployed: %5B${BUGGY_VERSION}%5D%28https://touchbit.org/repository/org/touchbit/buggy/buggy/${BUGGY_VERSION}/%29\""
